web: pip install -r requirements.txt && streamlit run streamlit_app/app.py --server.port $PORT --server.address 0.0.0.0
worker: pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port $PORT
